# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SudokuUI(object):
    def setupUi(self, SudokuUI):
        SudokuUI.setObjectName("SudokuUI")
        SudokuUI.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SudokuUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 40, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(300, 160, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.playButton.setFont(font)
        self.playButton.setObjectName("playButton")
        self.statisticsButton = QtWidgets.QPushButton(self.centralwidget)
        self.statisticsButton.setGeometry(QtCore.QRect(300, 250, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.statisticsButton.setFont(font)
        self.statisticsButton.setObjectName("statisticsButton")
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setGeometry(QtCore.QRect(300, 340, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.settingsButton.setFont(font)
        self.settingsButton.setObjectName("settingsButton")
        SudokuUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(SudokuUI)
        QtCore.QMetaObject.connectSlotsByName(SudokuUI)

    def retranslateUi(self, SudokuUI):
        _translate = QtCore.QCoreApplication.translate
        SudokuUI.setWindowTitle(_translate("SudokuUI", "Sudoku"))
        self.label.setText(_translate("SudokuUI", "Sudoku"))
        self.playButton.setText(_translate("SudokuUI", "Play"))
        self.statisticsButton.setText(_translate("SudokuUI", "Statistics"))
        self.settingsButton.setText(_translate("SudokuUI", "Settings"))
