# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StatisticsWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_statisticsWidget(object):
    def setupUi(self, statisticsWidget):
        statisticsWidget.setObjectName("statisticsWidget")
        statisticsWidget.resize(800, 600)
        self.backButton = QtWidgets.QPushButton(statisticsWidget)
        self.backButton.setGeometry(QtCore.QRect(10, 10, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")

        self.retranslateUi(statisticsWidget)
        QtCore.QMetaObject.connectSlotsByName(statisticsWidget)

    def retranslateUi(self, statisticsWidget):
        _translate = QtCore.QCoreApplication.translate
        statisticsWidget.setWindowTitle(_translate("statisticsWidget", "Form"))
        self.backButton.setText(_translate("statisticsWidget", "Go back"))
